services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - wordpress:/usr/src/wordpress
      - ./trunk/:/usr/src/wordpress/wp-content/plugins/login-awp/

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    depends_on:
      - mysql
    image: adminer
    ports:
      - 8080:8080

volumes:
  wordpress:
  mysql:
